### ISSUE TITLE
Flag tile bug

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#29]
obs_flat_tile.sh is not running. Complains that the list of tiles for flagging does not exist. I have tried different input variations and removing/adding lines to the flagging file. See examples below

```
> ./bin/obs_flag_tiles.sh -f processing/1217495184_tile_to_flag.txt 1217495184
flagging file doesn't exist: /astro/mwasci/phancock/D0009//processing/1217495184_tiles_to_flag.txt
not submitting job
> ./bin/obs_flag_tiles.sh -f 1217495184_tile_to_flag.txt 1217495184
flagging file doesn't exist: /astro/mwasci/phancock/D0009//processing/1217495184_tiles_to_flag.txt
not submitting job
> ./bin/obs_flag_tiles.sh 1217495184
realpath: missing operand
Try 'realpath --help' for more information.
flagging file doesn't exist: 
not submitting job
```

**Comment by PaulHancock** [comment]
Three issues here:
- I was looking at `obs_flag.sh` during debugging. Somehow this also tries to do the tile flagging. I have changed this so that `obs_flag.sh` does only the `aoflagger` flagging.
- There was a bug such that the supplied file was being ignored (now fixed).
- The default file should be called `..._tiles_to flag.txt` (plural) which is why the script didn't find your example file.
