### ISSUE TITLE
obs_dl.sh timed out after running "cotter"

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#3]
My last attempt at running the obs_dl.sh script on 1190018416 get up to the cotter step but did not calibrate. I ran the following:
./bin/obs_dl.sh 1190018416 0 1190018416 HerA

There were no errors from cotter. However, the download error file (dl_1190018416.e2375859) had the following:

bash: line 16: syntax error near unexpected token `fi'
bash: line 16: `fi'
slurmstepd: error: Exceeded step memory limit at some point.

The cotter and calibrate templates have run times of 4 hrs and 12 hrs, respectively. However, the download template only has 2 hrs. As all this is run using the download script I think the solution is to increase the runtime in the download template.  

If this is the problem, can I please increase the runtime in dl.tmpl to at least 12 hrs? What is the maximum we can use?

**Comment by PaulHancock** [comment]
There are two errors here:

The first is in dl.tmpl and it's just a syntax problem (complaining about the "fi'" statement). Obs download otherwise completed ok.

The cotter step completed fine, but the calibrate step is in error.

It seems that the error is due to a memory limit being being surpassed. We don't set a memory limit and usually andre's tools detect the limit and stick to it. I suspect that this is part of an issue with Pawsey reporting/calculating the memory avail/used incorrectly.

**Comment by PaulHancock** [comment]
As of c2f01494d5f13d69bd74d3b418d2af94f70773dc cotter is now run with the -absmem flag and the value of this is calculated from environment variables that are set by SLURM.

The problem is now usually fixed, but this all depends on SLURM setting appropriate values for the available memory.
